### ISSUE TITLE
Explore making the content on the homepage about options for mail in and early voting more visual

### ISSUE THREAD

**Issue by shannonmcharg** [OpenMaine/maineballot#131]

**Comment by jenniferthibault** [comment]
🖐️  I can pick this one up @shannonmcharg ! Can draft some ideas this weekend

**Comment by shannonmcharg** [comment]
Awesome!

**Comment by jenniferthibault** [comment]
Woof, sorry for the delay here, making this "more visual" inevitably led to some content re-architecting to make it work... and figuring out what the visual elements are, all in one go, and trying to keep it light!

This round includes:
- Drastically shortening the copy on the front page, and moving all the copy I cut into more detailed sections on the "How to vote in Maine" page
- Introducing a basic color palette we could start using. My preference is for this blue primary palette, which feels more closely related to the state flag color palette, without (I believe) leaning into partisanship. I think we could round this out with more pale yellows and forest-y greens through the site. 

![image](https://user-images.githubusercontent.com/11636908/91777025-c2a20b00-ebbc-11ea-8b04-1de09702bcdf.png)

Below the cutoff here is implied that the rest of the page is the same as is now, but I have some future ideas here too 🙃 

I'd still need to work on:
- Icons to fill the space, but I wanted to stop before I got tooooo far ahead.

I used the wayback machine to check how the site homepage was working when there was stuff on the ballot, and I *think* this layout will be flexible enough for future content, but *wasn't* trying to make it completely future-proof template yet, since the site is evolving.

Let me know what you think, and glad to pull out some hex codes & font sizes to get someone started on building it, and can work out those icon/illustrations!

**Comment by shannonmcharg** [comment]
@jenniferthibault This is great!  The only thing I would add is something under the vote by mail that lets people know they can return their ballot in person.  I think that's a question that's top of mind for many people right now.

@inomyabcs @curtisk Would one of you be able to build this?

**Comment by rentry** [comment]
![owl, beak open, turns its head to look at the camera](https://user-images.githubusercontent.com/15129890/91924362-4cb6a600-ec87-11ea-947d-21828e0ed1de.gif)

I recognize the name @jenniferthibault! So glad you're here!

**Comment by curtisk** [comment]
sure, send your design guidelines and can start framing it out, again this is focused on homepage for now?

**Comment by shannonmcharg** [comment]
Yes to homepage, for now.

**Comment by jenniferthibault** [comment]
Alright! Nice to meet you @curtisk . @shannonmcharg I added in the line on dropping off ballots instead of mailing. Good call!

This work is building some design guidelines for the site as we're going, so I tried to follow what I could infer from the existing site styles to not change too much, but instead build on what I saw there.

Here are some annotations on the structure (I'm guessing on the 12 column grid, so let's figure it out where I guessed wrong!), the image will get larger and more legible when you click it open into a new tab. Let me know if I can get you any more details to make it easier to build. 

Colors:
- darker blue: #205173 
- medium blue: #2F6585 
- light yellow: #EAE6D2 
- grey: #686867

The pink containers are what I'm thinking of as the max container-widths for text elements.

<img width="1361" alt="Screen Shot 2020-09-02 at 9 39 30 PM" src="https://user-images.githubusercontent.com/11636908/92061658-d5efda80-ed64-11ea-848a-5f1128f91d18.png">

**Comment by jenniferthibault** [comment]
And! Some **icon research**!
I found some [Civic icons and images ](https://electiontools.org/tool/civic-icons-and-images/#using-the-tool) from ElectionTools.org that are good to use through Creative Commons Attribution-ShareAlike 4.0 International License as long as we cite ElectionTools.org as the source of the images and make the images available free of cost (which will be covered by hosting them on GitHub). Wish I could make some great custom ones, but I'm no illustrator! 

What I like about these is that they don't scream at you, and fit with the logo's line art style well. A good-enough-for-now starter pack that doesn't feel out of place, annnnd there's more where that came from at electiontools.org when we need them. 

![image](https://user-images.githubusercontent.com/11636908/92062657-3e3fbb80-ed67-11ea-9d85-37974be5289a.png)

If you're ok with going this direction, here is a folder with .pngs at both the large & small size
[maine-vote_icons.zip](https://github.com/OpenMaine/maineballot/files/5165744/maine-vote_icons.zip)

**Comment by shannonmcharg** [comment]
These are all great.

**Comment by curtisk** [comment]
working on these changes, trying to take a second or three to grasp the already in place minimal-mistakes theme/scss and the Liquid markup in place so I'm not just throwing a bunch of one off code on top of all that's here already

**Comment by jenniferthibault** [comment]
Hey team! I'm taking an end-of-summer vacation and will be offline until next weekend. I'll check back then to see how I can help at that point!

**Comment by curtisk** [comment]
I'll have stuff to review tomorrow morning, afraid I'll miss something in pull request this late :)

**Comment by curtisk** [comment]
I think this one was completed a week ago; closing
